@startuml

title __EXCEPTIONS's Class Diagram__\n

  namespace Util {
    namespace Exceptions {
      class Util.Exceptions.IncorrectPayloadException {
          + IncorrectPayloadException()
      }
    }
  }


@enduml
