package Util;
// USE THIS INSTEAD OF DECLARING A BUNCH OF CONSTANT INTS
public enum RequestType
{
	UPDATE,
	LOGIN,
	LOGOUT,
	ERROR,
	DIAGNOSIS_GET_ALL_PATIENT,
	DIAGNOSIS_GET_ALL_DOCTOR,
	DIAGNOSIS_UPDATE_GIVEN_REFERENCE,
	DIAGNOSIS_CREATE_GIVEN_REFERENCE,
	DIAGNOSIS_REMOVE_GIVEN_REFERENCE,
	DOCTOR_GET_GIVEN_PATIENT,
	DOCTOR_GET_ALL,
	DOCTOR_GET_GIVEN_ID,
	DOCTOR_UPDATE_GIVEN_DOCTOR,
	DOCTOR_CREATE_GIVEN_DOCTOR,
	DOCTOR_REQUEST_GIVEN_NAME,
	DOCTOR_REQUEST_GIVEN_TIME,
	DOCTOR_REQUEST_GIVEN_DATE,
	DOCTOR_REMOVE_GIVEN_DOCTOR,
	PATIENT_GET_ALL
}
