@startuml

title __UTIL's Class Diagram__\n

  namespace Util {
    enum RequestType {
      DIAGNOSIS_CREATE_GIVEN_REFERENCE
      DIAGNOSIS_GET_ALL_DOCTOR
      DIAGNOSIS_GET_ALL_PATIENT
      DIAGNOSIS_REMOVE_GIVEN_REFERENCE
      DIAGNOSIS_UPDATE_GIVEN_REFERENCE
      DOCTOR_CREATE_GIVEN_DOCTOR
      DOCTOR_GET_ALL
      DOCTOR_GET_GIVEN_ID
      DOCTOR_GET_GIVEN_PATIENT
      DOCTOR_REMOVE_GIVEN_DOCTOR
      DOCTOR_REQUEST_GIVEN_DATE
      DOCTOR_REQUEST_GIVEN_NAME
      DOCTOR_REQUEST_GIVEN_TIME
      DOCTOR_UPDATE_GIVEN_DOCTOR
      ERROR
      LOGIN
      LOGOUT
      PATIENT_GET_ALL
      UPDATE
    }
  }
  

  namespace Util {
    class Util.RequestTypeRedux {
        {static} + ALL_PATHS : Collection<String>
        {static} + LOGIN : String
        {static} + UPDATE : String
    }
  }
  

  namespace Util {
    enum UserType {
      DOCTOR
      PATIENT
      STAFF
    }
  }


@enduml
