@startuml

title __Client's Class Diagram__\n

  namespace Clinic.Client {
    class Clinic.Client.Client {
        {static} + main()
    }
  }
  

  namespace Clinic.Client {
    class Clinic.Client.ClientSecretary {
        ~ avaiableID : int
        ~ tasklist : List<ClientTask>
        + ClientSecretary()
        + getDoctorAll()
        + getDoctorWithID()
        + handleMessageFromServer()
        + login()
        + logout()
        {static} + md5()
        + setMyClient()
        + setMyGUI()
        - prepareTask()
    }
  }
  

  namespace Clinic.Client {
    class Clinic.Client.ClientTask {
        ~ count : int
        ~ flag : Boolean
        ~ returnValue : Object
        + ClientTask()
        + getFlag()
        + getPayload()
        + getReturnValue()
        + run()
        + setFlag()
        + setPayload()
        + setReturnValue()
    }
  }
  

  Clinic.Client.ClientSecretary o-- Clinic.Client.Connection.MyClient : myClient
  Clinic.Client.ClientSecretary o-- Clinic.Client.GUI.MyGUI : myGUI
  Clinic.Client.ClientTask o-- Clinic.Core.Payload : payload


@enduml
