@startuml

title __Server's Class Diagram__\n

  namespace Clinic.Server {
    class Clinic.Server.Server {
        {static} + main()
    }
  }
  

  namespace Clinic.Server {
    class Clinic.Server.ServerDirector {
        + login()
    }
  }
  

  namespace Clinic.Server {
    class Clinic.Server.ServerSecretary {
        - avaiableID : int
        - clientTokens : List<Token>
        + ServerSecretary()
        + getMyServer()
        + handleMessageFromClient()
        + setMyServer()
        - findToken()
        - getDoctorWithID()
        - login()
        - logout()
    }
  }
  

  Clinic.Server.ServerSecretary o-- Clinic.Server.Connection.MyServer : myServer

@enduml
